# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9625d8f2521834946ee35ca86317aa1289928a274e16cdfb0dd7a33d24b1cc29fbaa141b501274a05ff1d37d1cea7e19be2d132af65c4c64e6a7a93b004a9fdd

test:
  secret_key_base: 99265f6a4309f2e5c9d21c760ec28d1e60be106c2f57a596ce49f8f16f156c3b04dbec0d5241a03af587c67530183ee6508eaf8a3af69bc32e772c69cd22ce37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
